/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.DefaultListModel;

/**
 *
 * @author Ikhsan
 */
public class Project4 extends javax.swing.JFrame {

    DefaultListModel<String> dlm;
    List<String> list = new ArrayList<>();
    Set<String> set = new HashSet<>();
    Map<Integer,String> map = new HashMap<>();
    
    /**
     * Creates new form Project4
     */
    public Project4() {
        initComponents();
        this.dlm = new DefaultListModel<>();
        this.jList1.setModel(dlm);
        
        label_listTersimpan.setText("List tersimpan: "+list.size());
        label_setTersimpan.setText("Set tersimpan: "+set.size());
        label_mapTersimpan.setText("Map tersimpan: "+map.size());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btn_saveList = new javax.swing.JButton();
        btn_insertList = new javax.swing.JButton();
        label_listTersimpan = new javax.swing.JLabel();
        btn_saveSet = new javax.swing.JButton();
        btn_insertSet = new javax.swing.JButton();
        label_setTersimpan = new javax.swing.JLabel();
        btn_saveMap = new javax.swing.JButton();
        btn_insertMap = new javax.swing.JButton();
        label_mapTersimpan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textFld_itemName = new javax.swing.JTextField();
        btn_clearAll = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        btn_saveList.setText("save to List ->");
        btn_saveList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveListActionPerformed(evt);
            }
        });

        btn_insertList.setText("<- insert data List");
        btn_insertList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertListActionPerformed(evt);
            }
        });

        label_listTersimpan.setText("List tersimpan: ");

        btn_saveSet.setText("save to Set ->");
        btn_saveSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveSetActionPerformed(evt);
            }
        });

        btn_insertSet.setText("<- insert data Set");
        btn_insertSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertSetActionPerformed(evt);
            }
        });

        label_setTersimpan.setText("Set tersimpan: ");

        btn_saveMap.setText("save to Map ->");
        btn_saveMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveMapActionPerformed(evt);
            }
        });

        btn_insertMap.setText("<- insert data Map");
        btn_insertMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertMapActionPerformed(evt);
            }
        });

        label_mapTersimpan.setText("Map tersimpan: ");

        jLabel1.setText("Item name:");

        textFld_itemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFld_itemNameActionPerformed(evt);
            }
        });

        btn_clearAll.setText("clear all");
        btn_clearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearAllActionPerformed(evt);
            }
        });

        btn_add.setText("add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_update.setText("update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setText("delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clearAll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_add)
                        .addGap(18, 18, 18)
                        .addComponent(btn_update)
                        .addGap(18, 18, 18)
                        .addComponent(btn_delete))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_saveList)
                            .addGap(18, 18, 18)
                            .addComponent(label_listTersimpan))
                        .addComponent(btn_insertList)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_saveSet)
                            .addGap(18, 18, 18)
                            .addComponent(label_setTersimpan))
                        .addComponent(btn_insertSet)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_saveMap)
                            .addGap(18, 18, 18)
                            .addComponent(label_mapTersimpan))
                        .addComponent(btn_insertMap)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(textFld_itemName))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_saveList)
                            .addComponent(label_listTersimpan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_insertList)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_saveSet)
                            .addComponent(label_setTersimpan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_insertSet)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_saveMap)
                            .addComponent(label_mapTersimpan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_insertMap)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(textFld_itemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_clearAll)
                    .addComponent(btn_add)
                    .addComponent(btn_update)
                    .addComponent(btn_delete))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_saveListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveListActionPerformed
        // TODO add your handling code here:
        if(!list.isEmpty()){
            list.clear();
        }
        
        for(int i=0; i<dlm.size(); i++){
            list.add(dlm.getElementAt(i));
        }
        label_listTersimpan.setText("List tersimpan: "+list.size());
    }//GEN-LAST:event_btn_saveListActionPerformed

    private void btn_insertListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertListActionPerformed
        // TODO add your handling code here:
        for(String item: list){
            dlm.addElement(item);
        }
    }//GEN-LAST:event_btn_insertListActionPerformed

    private void btn_saveSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveSetActionPerformed
        // TODO add your handling code here:
        if(!set.isEmpty()){
            set.clear();
        }
        
        for(int i=0; i<dlm.size(); i++){
            set.add(dlm.getElementAt(i));
        }
        label_setTersimpan.setText("Set tersimpan: "+set.size());
    }//GEN-LAST:event_btn_saveSetActionPerformed

    private void btn_insertSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertSetActionPerformed
        // TODO add your handling code here:
        for(String item: set){
            dlm.addElement(item);
        }
    }//GEN-LAST:event_btn_insertSetActionPerformed

    private void btn_saveMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveMapActionPerformed
        // TODO add your handling code here:
        if(!map.isEmpty()){
            map.clear();
        }
        
        for(int i=0; i<dlm.size(); i++){
            map.put(i, dlm.getElementAt(i));
        }
        label_mapTersimpan.setText("Map tersimpan: "+map.size());
    }//GEN-LAST:event_btn_saveMapActionPerformed

    private void btn_insertMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertMapActionPerformed
        // TODO add your handling code here:
        Set<Integer> set = map.keySet();
        
        for(Integer key: set){
            dlm.addElement(map.get(key));
        }
    }//GEN-LAST:event_btn_insertMapActionPerformed

    private void textFld_itemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFld_itemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFld_itemNameActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        dlm.addElement(textFld_itemName.getText());
//        membersihkan txtField
        textFld_itemName.setText("");
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:        
        dlm.setElementAt(textFld_itemName.getText(), jList1.getSelectedIndex());
//        membersihkan txtField
        textFld_itemName.setText("");
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        dlm.remove(jList1.getSelectedIndex());                
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_clearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearAllActionPerformed
        // TODO add your handling code here:
        dlm.removeAllElements();
    }//GEN-LAST:event_btn_clearAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Project4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Project4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Project4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Project4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Project4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_clearAll;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_insertList;
    private javax.swing.JButton btn_insertMap;
    private javax.swing.JButton btn_insertSet;
    private javax.swing.JButton btn_saveList;
    private javax.swing.JButton btn_saveMap;
    private javax.swing.JButton btn_saveSet;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_listTersimpan;
    private javax.swing.JLabel label_mapTersimpan;
    private javax.swing.JLabel label_setTersimpan;
    private javax.swing.JTextField textFld_itemName;
    // End of variables declaration//GEN-END:variables

}
