/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdbc.utilities;

import java.util.List;
import javax.swing.DefaultListModel;
import jdbc.dao.dao.MysklMahasiswaDAO;
import jdbc.dao.transferObject.Mahasiswa;

/**
 *
 * @author Ikhsan
 */
public class Interface extends javax.swing.JFrame {
    DefaultListModel dlmID, dlmName;
    
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        this.dlmID = new DefaultListModel<>();
        this.dlmName = new DefaultListModel<>();
        this.list_ID.setModel(dlmID);
        this.list_nama.setModel(dlmName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list_ID = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_nama = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        button_AmbilSemuaData = new javax.swing.JButton();
        textField_Nama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        button_Tambah = new javax.swing.JButton();
        textField_updateID = new javax.swing.JTextField();
        textField_updateNama = new javax.swing.JTextField();
        button_Edit = new javax.swing.JButton();
        textField_delete = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        list_ID.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list_ID);

        list_nama.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(list_nama);

        jLabel1.setText("ID");

        jLabel2.setText("Nama");

        jLabel3.setText("KELOLA DATA MAHASISWA");

        button_AmbilSemuaData.setText("Ambil Semua Data");
        button_AmbilSemuaData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_AmbilSemuaDataActionPerformed(evt);
            }
        });

        jLabel4.setText("Nama");

        button_Tambah.setText("Tambah");
        button_Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_TambahActionPerformed(evt);
            }
        });

        textField_updateID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_updateIDActionPerformed(evt);
            }
        });

        button_Edit.setText("Edit");
        button_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_EditActionPerformed(evt);
            }
        });

        textField_delete.setText("0000");
        textField_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_deleteActionPerformed(evt);
            }
        });

        jButton4.setText("Hapus");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(110, 110, 110)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textField_Nama)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(button_AmbilSemuaData)
                                    .addComponent(jLabel4)
                                    .addComponent(button_Tambah))
                                .addGap(0, 114, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textField_updateID)
                                    .addComponent(textField_delete, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton4)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textField_updateNama)
                                        .addGap(18, 18, 18)
                                        .addComponent(button_Edit)))))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(button_AmbilSemuaData)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(4, 4, 4)
                        .addComponent(textField_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_Tambah)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textField_updateID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textField_updateNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_Edit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textField_delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_AmbilSemuaDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_AmbilSemuaDataActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_button_AmbilSemuaDataActionPerformed

    private void update(){
        dlmID.clear();dlmName.clear();
        
        MysklMahasiswaDAO myskl = new MysklMahasiswaDAO();
        List<Mahasiswa> datas = myskl.getAll();
        
        for(Mahasiswa data: datas){
            dlmID.addElement(data.getId());
            dlmName.addElement(data.getNama());
        }
    }
    
    private void button_TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_TambahActionPerformed
        // TODO add your handling code here:
        MysklMahasiswaDAO myskl = new MysklMahasiswaDAO();
        Mahasiswa mhsAdd = new Mahasiswa();
        mhsAdd.setNama(textField_Nama.getText());
        myskl.add(mhsAdd);
        update();
        textField_Nama.setText("");
    }//GEN-LAST:event_button_TambahActionPerformed

    private void textField_updateIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_updateIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_updateIDActionPerformed

    private void button_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_EditActionPerformed
        // TODO add your handling code here:
        MysklMahasiswaDAO myskl = new MysklMahasiswaDAO();
        Mahasiswa mhsUpdate = new Mahasiswa();
        int id = Integer.valueOf(textField_updateID.getText());
        mhsUpdate.setId(id);
        mhsUpdate.setNama(textField_updateNama.getText());
        myskl.update(mhsUpdate);
        update();
        textField_updateID.setText("");
        textField_updateNama.setText("");
    }//GEN-LAST:event_button_EditActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        MysklMahasiswaDAO myskl = new MysklMahasiswaDAO();
        int id = Integer.valueOf(textField_delete.getText());
        myskl.delete(id);
        update();
        textField_delete.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void textField_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_AmbilSemuaData;
    private javax.swing.JButton button_Edit;
    private javax.swing.JButton button_Tambah;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> list_ID;
    private javax.swing.JList<String> list_nama;
    private javax.swing.JTextField textField_Nama;
    private javax.swing.JTextField textField_delete;
    private javax.swing.JTextField textField_updateID;
    private javax.swing.JTextField textField_updateNama;
    // End of variables declaration//GEN-END:variables
}
