package aClient;

import dao.KamusDAO;
import java.util.List;
import javax.swing.DefaultListModel;
import transferObject.Kamus;
import utilities.MysklUtility;

public class FrameKamus extends javax.swing.JFrame {

    KamusDAO kmsDAO = new KamusDAO();
    DefaultListModel<String> dlm1;
    DefaultListModel<String> dlm2;

    /**
     * Creates new form FrameUtama
     */
    public FrameKamus() {
        initComponents();

        dlm1 = new DefaultListModel<>();
        dlm2 = new DefaultListModel<>();
        jListIndo.setModel(dlm1);
        jListEng.setModel(dlm2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAmbilData = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListIndo = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListEng = new javax.swing.JList<>();
        jLabelIndo = new javax.swing.JLabel();
        jLabelEng = new javax.swing.JLabel();
        txtFld_terjemah = new javax.swing.JTextField();
        jLabelKataIndo = new javax.swing.JLabel();
        jLabelTerjemahEng = new javax.swing.JLabel();
        lbl_HasilTerjemah = new javax.swing.JLabel();
        btn_Terjemahkan = new javax.swing.JButton();
        jTextFieldTambahIndo = new javax.swing.JTextField();
        jTextFieldTambahEng = new javax.swing.JTextField();
        jLabelIndoData = new javax.swing.JLabel();
        jLabelEngData = new javax.swing.JLabel();
        jButton3TambahKeDB = new javax.swing.JButton();
        jLabelTambahData = new javax.swing.JLabel();
        jButtonHapusData = new javax.swing.JButton();
        jTextFieldDataDihapus = new javax.swing.JTextField();
        jLabelDelete = new javax.swing.JLabel();
        jTextFieldEditIndo = new javax.swing.JTextField();
        jTextFieldEditEng = new javax.swing.JTextField();
        jLabelEditIndo = new javax.swing.JLabel();
        jLabelEditEng = new javax.swing.JLabel();
        jButtonEdit = new javax.swing.JButton();
        jLabelEditMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonAmbilData.setText("Baca data kamus dari DB");
        jButtonAmbilData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAmbilDataActionPerformed(evt);
            }
        });

        jListIndo.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListIndoValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListIndo);

        jScrollPane2.setViewportView(jListEng);

        jLabelIndo.setText("Indonesia");

        jLabelEng.setText("English");

        jLabelKataIndo.setText("Indonesia");

        jLabelTerjemahEng.setText("English : ");

        lbl_HasilTerjemah.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_HasilTerjemah.setText("Terjemahan");

        btn_Terjemahkan.setText("Terjemahkan");
        btn_Terjemahkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TerjemahkanActionPerformed(evt);
            }
        });

        jLabelIndoData.setText("Indo");

        jLabelEngData.setText("Eng");

        jButton3TambahKeDB.setText("Tambahkan");
        jButton3TambahKeDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3TambahKeDBActionPerformed(evt);
            }
        });

        jLabelTambahData.setText("Tambah Data ke Database Kamus:");

        jButtonHapusData.setText("Hapus data");
        jButtonHapusData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusDataActionPerformed(evt);
            }
        });

        jLabelDelete.setText("Hapus Data terseleksi");

        jLabelEditIndo.setText("Indo");

        jLabelEditEng.setText("Eng");

        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jLabelEditMenu.setText("Edit Data:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonAmbilData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelIndo)
                        .addGap(34, 34, 34)
                        .addComponent(jLabelEng)))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jTextFieldDataDihapus)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonHapusData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDelete)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelEditMenu)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabelEditIndo)
                                        .addGap(10, 10, 10)
                                        .addComponent(jTextFieldEditIndo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabelEditEng)
                                        .addGap(10, 10, 10)
                                        .addComponent(jTextFieldEditEng, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelKataIndo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFld_terjemah, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelTerjemahEng)
                                        .addGap(5, 5, 5)
                                        .addComponent(lbl_HasilTerjemah, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelTambahData)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabelIndoData)
                                        .addGap(10, 10, 10)
                                        .addComponent(jTextFieldTambahIndo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabelEngData)
                                        .addGap(10, 10, 10)
                                        .addComponent(jTextFieldTambahEng, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_Terjemahkan)
                                    .addComponent(jButton3TambahKeDB))))
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jButtonAmbilData)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIndo)
                            .addComponent(jLabelEng))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelKataIndo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_Terjemahkan)
                                .addGap(96, 96, 96)
                                .addComponent(jButton3TambahKeDB, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtFld_terjemah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTerjemahEng)
                                    .addComponent(lbl_HasilTerjemah))
                                .addGap(53, 53, 53)
                                .addComponent(jLabelTambahData)
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabelIndoData))
                                    .addComponent(jTextFieldTambahIndo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabelEngData))
                                    .addComponent(jTextFieldTambahEng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelEditMenu)
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabelEditIndo))
                                    .addComponent(jTextFieldEditIndo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabelEditEng))
                                    .addComponent(jTextFieldEditEng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(jLabelDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDataDihapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHapusData))))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAmbilDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAmbilDataActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_jButtonAmbilDataActionPerformed

    private void btn_TerjemahkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TerjemahkanActionPerformed
        // TODO add your handling code here:  
        lbl_HasilTerjemah.setText(kmsDAO.search(txtFld_terjemah.getText()));
    }//GEN-LAST:event_btn_TerjemahkanActionPerformed

    private void jListIndoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListIndoValueChanged
        // TODO add your handling code here:

        jTextFieldEditIndo.setText(jListIndo.getSelectedValue());
        jTextFieldDataDihapus.setText(jListIndo.getSelectedValue());
        if (jListIndo.isSelectedIndex(jListIndo.getSelectedIndex())) {
            jTextFieldEditEng.setText(dlm2.getElementAt(jListIndo.getSelectedIndex()));
        }
    }//GEN-LAST:event_jListIndoValueChanged

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
        Kamus kmsUpd = kmsDAO.MakeKamusObject();
        String s = jListIndo.getSelectedValue();
        Integer id = kmsDAO.searchId(s);

        System.out.println("Coba: " + id);
        kmsUpd.setId(id);
        kmsUpd.setInd(jTextFieldEditIndo.getText());
        kmsUpd.setEng(jTextFieldEditEng.getText());
        kmsDAO.update(kmsUpd);
        update();
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButton3TambahKeDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3TambahKeDBActionPerformed
        // TODO add your handling code here:
        Kamus kmsAdd = kmsDAO.MakeKamusObject();
        kmsAdd.setInd(jTextFieldTambahIndo.getText());
        kmsAdd.setEng(jTextFieldTambahEng.getText());
        kmsDAO.add(kmsAdd);
        update();
    }//GEN-LAST:event_jButton3TambahKeDBActionPerformed

    private void jButtonHapusDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusDataActionPerformed
        // TODO add your handling code here:
        Integer i = kmsDAO.searchId(jTextFieldDataDihapus.getText());
        kmsDAO.delete(i);
        update();
    }//GEN-LAST:event_jButtonHapusDataActionPerformed

    private void update() {
        dlm1.clear();
        dlm2.clear();

        List<Kamus> kmses = kmsDAO.getAll();
        for (Kamus kms : kmses) {
            dlm1.addElement("" + kms.getInd() + "");
            dlm2.addElement("" + kms.getEng() + "");
        }
        jTextFieldTambahIndo.setText("");
        jTextFieldTambahEng.setText("");
        jTextFieldEditIndo.setText("");
        jTextFieldEditEng.setText("");
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameKamus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameKamus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameKamus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameKamus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameKamus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Terjemahkan;
    private javax.swing.JButton jButton3TambahKeDB;
    private javax.swing.JButton jButtonAmbilData;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonHapusData;
    private javax.swing.JLabel jLabelDelete;
    private javax.swing.JLabel jLabelEditEng;
    private javax.swing.JLabel jLabelEditIndo;
    private javax.swing.JLabel jLabelEditMenu;
    private javax.swing.JLabel jLabelEng;
    private javax.swing.JLabel jLabelEngData;
    private javax.swing.JLabel jLabelIndo;
    private javax.swing.JLabel jLabelIndoData;
    private javax.swing.JLabel jLabelKataIndo;
    private javax.swing.JLabel jLabelTambahData;
    private javax.swing.JLabel jLabelTerjemahEng;
    private javax.swing.JList<String> jListEng;
    private javax.swing.JList<String> jListIndo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldDataDihapus;
    private javax.swing.JTextField jTextFieldEditEng;
    private javax.swing.JTextField jTextFieldEditIndo;
    private javax.swing.JTextField jTextFieldTambahEng;
    private javax.swing.JTextField jTextFieldTambahIndo;
    private javax.swing.JLabel lbl_HasilTerjemah;
    private javax.swing.JTextField txtFld_terjemah;
    // End of variables declaration//GEN-END:variables

}
