package undip.ganjil;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Scanner;
import javax.swing.DefaultListModel;

public class JFrameGanjil extends javax.swing.JFrame {

    FileReader fr;
    DefaultListModel<Integer> dlmIsiFile;
    DefaultListModel<Integer> dlmHasilDeteksi;
    List<String> isiFile = new ArrayList<>();

    List<Integer> urutkan1 = new ArrayList<>();
    List<Integer> urutkan2 = new ArrayList<>();

    /**
     * Creates new form JFrameGanjil
     */
    public JFrameGanjil() {
        initComponents();
        dlmIsiFile = new DefaultListModel<>();
        dlmHasilDeteksi = new DefaultListModel<>();
        jListBilangan.setModel(dlmIsiFile);
        jListDeteksi.setModel(dlmHasilDeteksi);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListBilangan = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListDeteksi = new javax.swing.JList<>();
        jButtonBacaFile = new javax.swing.JButton();
        jButtonDetekGanjil = new javax.swing.JButton();
        txtFld_jml2 = new javax.swing.JTextField();
        jButtonUrutkan = new javax.swing.JButton();
        txtFld_jumlah1 = new javax.swing.JTextField();
        jButtonUrutBil = new javax.swing.JButton();
        jTextFieldNamaFile = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jScrollPane1.setViewportView(jListBilangan);

        jScrollPane2.setViewportView(jListDeteksi);

        jButtonBacaFile.setText("Baca File");
        jButtonBacaFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBacaFileActionPerformed(evt);
            }
        });

        jButtonDetekGanjil.setText("deteksi ganjil");
        jButtonDetekGanjil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetekGanjilActionPerformed(evt);
            }
        });

        txtFld_jml2.setText("Jumlah = 0");

        jButtonUrutkan.setText("Urutkan");
        jButtonUrutkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUrutkanActionPerformed(evt);
            }
        });

        txtFld_jumlah1.setText("Jumlah = 0");
        txtFld_jumlah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFld_jumlah1ActionPerformed(evt);
            }
        });

        jButtonUrutBil.setText("Urutkan");
        jButtonUrutBil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUrutBilActionPerformed(evt);
            }
        });

        jTextFieldNamaFile.setText("bilangan.txt");

        jLabel1.setText("Nama File");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("PENDETEKSI BILANGAN GANJIL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonBacaFile, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jButtonDetekGanjil))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFld_jumlah1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(txtFld_jml2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonUrutBil, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jButtonUrutkan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNamaFile, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNamaFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBacaFile)
                    .addComponent(jButtonDetekGanjil))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFld_jumlah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFld_jml2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonUrutBil)
                    .addComponent(jButtonUrutkan))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBacaFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBacaFileActionPerformed
        dlmIsiFile.clear();
        isiFile.clear();
        urutkan1.clear();
        isiFile = bacaFile(jTextFieldNamaFile.getText());
        int jumlah = 0;
        for (int i = 0; i < isiFile.size() - 1; i++) {
            try {
                Integer angka = Integer.parseInt(isiFile.get(i)); // ubah menjadi integer
                dlmIsiFile.addElement(angka);
                urutkan1.add(angka);
                jumlah = jumlah + angka;
            } catch (NumberFormatException e) {
                System.out.println("NumberFormatException : " + e.getMessage());
            }
        }
        txtFld_jumlah1.setText("" + jumlah);
    }//GEN-LAST:event_jButtonBacaFileActionPerformed

    private void txtFld_jumlah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFld_jumlah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFld_jumlah1ActionPerformed

    private void jButtonUrutBilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUrutBilActionPerformed
        // TODO add your handling code here:
        dlmIsiFile.clear();
        Collections.sort(urutkan1);
        for (int i = 0; i <= urutkan1.size() - 1; i++) {
            try {
                dlmIsiFile.addElement(urutkan1.get(i));
            } catch (NumberFormatException e) {
                System.out.println("NumberFormatException : " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonUrutBilActionPerformed

    private void jButtonDetekGanjilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetekGanjilActionPerformed
        // TODO add your handling code here:
        int jumlah = 0;
        urutkan2.clear();
        dlmHasilDeteksi.clear();
        for (int i = 0; i < dlmIsiFile.getSize() - 1; i++) {
            if(dlmIsiFile.getElementAt(i)%2!=0){
                int angka = dlmIsiFile.getElementAt(i);
                dlmHasilDeteksi.addElement(angka);
                urutkan2.add(angka);
                jumlah = jumlah + angka;
            }
        }
        txtFld_jml2.setText(""+jumlah);
    }//GEN-LAST:event_jButtonDetekGanjilActionPerformed

    private void jButtonUrutkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUrutkanActionPerformed
        // TODO add your handling code here:
        Collections.sort(urutkan2);
        dlmHasilDeteksi.clear();
        for(int i=0; i<=urutkan2.size()-1; i++){
            dlmHasilDeteksi.addElement(urutkan2.get(i));
        }
    }//GEN-LAST:event_jButtonUrutkanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameGanjil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameGanjil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameGanjil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameGanjil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameGanjil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBacaFile;
    private javax.swing.JButton jButtonDetekGanjil;
    private javax.swing.JButton jButtonUrutBil;
    private javax.swing.JButton jButtonUrutkan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<Integer> jListBilangan;
    private javax.swing.JList<Integer> jListDeteksi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldNamaFile;
    private javax.swing.JTextField txtFld_jml2;
    private javax.swing.JTextField txtFld_jumlah1;
    // End of variables declaration//GEN-END:variables

    /**
     * Membaca file
     *
     * @return List of String
     */
    private List<String> bacaFile(String namaFile) {
        List<String> isiFile = new ArrayList<>();
        try {
            fr = new FileReader(namaFile);
            Scanner scan = new Scanner(fr);
            while (scan.hasNextLine()) {
                isiFile.add(scan.nextLine());
            }
        } catch (FileNotFoundException ex) {
            System.out.println(ex);
        }
        return isiFile;
    }

}
