/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.util.List;
import javax.swing.DefaultListModel;
import jdbc.dao.dao.MysqlMahasiswaDAO;
import jdbc.dao.transferObject.Mahasiswa;
import jdbc.utilities.MysqlUtility;

/**
 *
 * @author User
 */
public class JFrameDAO extends javax.swing.JFrame {

    //Build Connection to DB
    MysqlMahasiswaDAO mhsDAO = new MysqlMahasiswaDAO();

    DefaultListModel<String> dlm1;
    DefaultListModel<String> dlm2;

    /**
     * Creates new form JFrameDAO
     */
    public JFrameDAO() {
        initComponents();

        //Build Connection to DB
        MysqlUtility.getConnection();

        //Init List ID
        this.dlm1 = new DefaultListModel<>();
        this.jListID.setModel(dlm1);

        //Init List Nama
        this.dlm2 = new DefaultListModel<>();
        this.jListNama.setModel(dlm2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListID = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListNama = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jButtonSelectAll = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldInsertNama = new javax.swing.JTextField();
        jButtonInsert = new javax.swing.JButton();
        jTextFieldUpdateID = new javax.swing.JTextField();
        jTextFieldUpdateNama = new javax.swing.JTextField();
        jButtonUpdate = new javax.swing.JButton();
        jTextFieldDeleteID = new javax.swing.JTextField();
        jTextFieldDeleteNama = new javax.swing.JTextField();
        jButtonDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID");

        jListID.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListIDValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListID);

        jLabel2.setText("NAMA");

        jListNama.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListNamaValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListNama);

        jLabel3.setText("KELOLA DATA MAHASISWA");

        jButtonSelectAll.setText("AMBIL SEMUA DATA");
        jButtonSelectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectAllActionPerformed(evt);
            }
        });

        jLabel4.setText("nama :");

        jButtonInsert.setText("Tambahkan");
        jButtonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("Edit");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Hapus");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonSelectAll)
                            .addComponent(jLabel4)
                            .addComponent(jButtonInsert)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldUpdateID, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                    .addComponent(jTextFieldDeleteID))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldUpdateNama)
                                    .addComponent(jTextFieldDeleteNama, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jTextFieldInsertNama)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(62, 62, 62))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSelectAll)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldInsertNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonInsert)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldUpdateID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldUpdateNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonUpdate))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDeleteID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDeleteNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDelete))
                        .addGap(0, 66, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectAllActionPerformed
        // TODO add your handling code here:
        mahasiswaSelectAll();
    }//GEN-LAST:event_jButtonSelectAllActionPerformed

    private void jButtonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertActionPerformed
        // TODO add your handling code here:
        Mahasiswa mhsAdd = mhsDAO.makeMhsObject();
        mhsAdd.setNama(jTextFieldInsertNama.getText());
        mhsDAO.add(mhsAdd);

        mahasiswaSelectAll();
        jTextFieldInsertNama.setText("");
        jTextFieldDeleteNama.setText("");
        jTextFieldUpdateNama.setText("");
    }//GEN-LAST:event_jButtonInsertActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        Mahasiswa mhsUpd = mhsDAO.makeMhsObject();
        mhsUpd.setId(Integer.parseInt(jTextFieldUpdateID.getText()));
        mhsUpd.setNama(jTextFieldUpdateNama.getText());

        mhsDAO.update(mhsUpd);

        jTextFieldDeleteID.setText("");
        jTextFieldDeleteNama.setText("");
        jTextFieldUpdateID.setText("");
        jTextFieldUpdateNama.setText("");

        mahasiswaSelectAll();
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        Mahasiswa mhsDel = mhsDAO.makeMhsObject();
        mhsDel.setId(Integer.parseInt(jTextFieldDeleteID.getText()));
        mhsDel.setNama(jTextFieldDeleteNama.getText());

        mhsDAO.delete(mhsDel.getId());

        jTextFieldDeleteID.setText("");
        jTextFieldDeleteNama.setText("");
        jTextFieldUpdateID.setText("");
        jTextFieldUpdateNama.setText("");

        mahasiswaSelectAll();
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jListIDValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListIDValueChanged
        // TODO add your handling code here:

        jTextFieldDeleteID.setText(jListID.getSelectedValue());
        jTextFieldUpdateID.setText(jListID.getSelectedValue());

        if (jListID.isSelectedIndex(jListID.getSelectedIndex())) {
            jTextFieldUpdateNama.setText(dlm2.getElementAt(jListID.getSelectedIndex()));
            jTextFieldDeleteNama.setText(dlm2.getElementAt(jListID.getSelectedIndex()));
        }
    }//GEN-LAST:event_jListIDValueChanged

    private void jListNamaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListNamaValueChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_jListNamaValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameDAO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameDAO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameDAO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameDAO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameDAO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonInsert;
    private javax.swing.JButton jButtonSelectAll;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jListID;
    private javax.swing.JList<String> jListNama;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldDeleteID;
    private javax.swing.JTextField jTextFieldDeleteNama;
    private javax.swing.JTextField jTextFieldInsertNama;
    private javax.swing.JTextField jTextFieldUpdateID;
    private javax.swing.JTextField jTextFieldUpdateNama;
    // End of variables declaration//GEN-END:variables

    private void mahasiswaSelectAll() {
        dlm1.clear();
        dlm2.clear();

        List<Mahasiswa> mhsID = mhsDAO.getAll();
        for (Mahasiswa person : mhsID) {
            dlm1.addElement("" + person.getId() + "");
        }

        List<Mahasiswa> mhsNama = mhsDAO.getAll();
        for (Mahasiswa person : mhsNama) {
            dlm2.addElement(person.getNama());
        }
    }
}
